---
- name: Install necessary packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - curl
    - psmisc
    - rsync
    - docker-compose
    - jq
  
- name: Install pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3-pip 
    - python3-dev 
    - python3-wheel 
    - python3-psycopg2
    - libpq-dev

- name: Install necessary python packages
  pip:
    name:
      - setuptools
      - docker
      - docker-compose
      - requests
    state: latest

