---
- name: Установка переменной nginx_dir
  set_fact:
    nginx_dir: "{{ '/opt/nginx' if is_nginx_in_docker else '/etc/nginx' }}"
  tags: copy_nginx_configs
    
- name: Копирование конфигурационных файлов Nginx
  template:
    src: "{{ item.src }}"
    dest: "{{ nginx_dir }}/{{ item.dest }}"
  loop:
    - { src: "nginx.conf.j2", dest: "nginx.conf" }
    - { src: "default.conf.j2", dest: "conf.d/default.conf" }
    - { src: "proxy.conf", dest: "proxy.conf" }
    - { src: "ssl.conf", dest: "ssl.conf" }
  notify:
    - Перезапуск службы Nginx
    - Restart nginx-docker
  tags: copy_nginx_configs

- name: Создание символической ссылки для сертификатов
  file:
    src: "/etc/ssl/{{ item.src }}"
    dest: "{{ nginx_dir }}/ssl/{{ item.dest }}"
    state: link
  loop:
    - { src: "private/mycert.key", dest: "mycert.key" }
    - { src: "certs/mycert.crt", dest: "mycert.crt" }
